version: "3.9"

services:
  hapi-fhir:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-server

    ports:
      - "8080:8080"

    volumes:
      - hapi-data:/data

volumes:
  hapi-data:
